server:
  port: 8082
application:
  name: log-scout-plugin
  version: 1.0.0
  base-url:
    context: /${application.name}/${application.version}

logging:
  level:
    root: INFO
    org:
      springframework.web: INFO
      hibernate: ERROR
    com: DEBUG  # Or INFO, depending on your need

  pattern:
    console: >
      %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} 
      %clr(TRACE_ID: %X{TRACE_ID}){green} 
      %clr([%thread]){cyan} 
      %clr(%-5level){magenta} 
      %clr(%logger{36}){yellow} 
      %clr(:){red} 
      %msg%n%throwable
  file:
    name: C:\Users\ASUS\OneDrive\Documents\logs\${application.name}\${application.version}\elk-stack.log

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
    health:
      show-details: always
  metrics:
    tags:
      application: ${application.name}
